### PR TITLE
add iiif_service config option to allow external IIIF server

### PR DESCRIPTION
**Pull request by dunn**
This is an attempt to extract references to RIIIF into a new `RiiifService` so that in the future applications can swap it out with a service module that connects to an external IIIF server (like Cantaloupe) instead.

There are still references I haven't removed yet, and this includes ~~https://github.com/projectblacklight/spotlight/pull/2845~~ and https://github.com/projectblacklight/spotlight/pull/2846 for ease of development.

### CODE REVIEW

**Comment by dunn** [comment]
bizarrely, only seeing this error on Ruby 3: https://github.com/projectblacklight/spotlight/actions/runs/3201034405/jobs/5228805376#step:5:4829

**Comment by dunn** [comment]
i'm not sure what's happening here but it seems like the object isn't being saved? https://github.com/projectblacklight/spotlight/actions/runs/3221407448/jobs/5269301341#step:5:4853

**Comment by dunn** [comment]
can confirm this allows spotlight to use an external IIIF server (in this case, cantaloupe): https://gitlab.com/surfliner/surfliner/-/merge_requests/2767

**Review by hackartisan — COMMENTED** [review]
Great idea. Thanks for doing this! I think it looks good but it would be nice for someone else to review as well.

**Review by tpendragon — APPROVED** [review]

**Pull request merged**
