### PR TITLE
allow multiple browse windows to be open at the same time

### LINKED ISSUE #3242: Bug: can't have two browse pages open with correct breadcrumbs
### Description
The breadcrumbs update to the latest breadcrumb

### Steps to reproduce
(create two browse categories with one result in each)
1. Open a browse page.
2. Choose a browse category
3. open one of the items in the browse category
4. Open a new tab
5. Choose a different browse category from step 2
6. open one of the items in the browse category
7. Refresh your first tab
8. You should see the second tab's browse breadcrumbs

### PR DESCRIPTION
**Pull request by dnoneill**
closes https://github.com/sul-dlss/exhibits/issues/2585
closes #3242

### CODE REVIEW

**Comment by jcoyne** [comment]
Related to https://github.com/projectblacklight/blacklight/issues/2558

**Review by corylown — COMMENTED** [review]
I don't think this fixes the issue described in https://github.com/sul-dlss/exhibits/issues/2585

In my testing app still shows a browse category in the breadcrumb under the conditions described in the issue.

**Comment by dnoneill** [comment]
@corylown It was fixing another issue which I have since linked. It should now fix both issues.

**Review by corylown — COMMENTED** [review]
Still seeing some pretty odd behavior from the breadcrumbs. This does appear to fix the issue with opening two browse categories in different windows. But if I have navigated to an item from a browse category and then go directly to another item in a different window the breadcrumb says "search results" but the link goes to the last browse category I visited.
Screenshot 2024-10-25 at 9 33 16 AM

**Comment by dnoneill** [comment]
closing due to consensus this seems somewhat unsolvable.

**Pull request closed without merging**
