### PR TITLE
Change permissions in CI

### PR DESCRIPTION
**Pull request by taylor-steve**
Trying to fix CI error:

`[EngineCart] Unable to find test application dependencies in /home/runner/work/spotlight/spotlight/.internal_test_app/Gemfile, using placeholder dependencies`

### CODE REVIEW

**Comment by jcoyne** [comment]
@taylor-steve this message is not an error, it's the correct behavior for engine_cart telling you what it is doing.

**Comment by taylor-steve** [comment]
I was too quick to copy and paste the first message I saw. Cory and I are trying to figure this out. We assumed it was more the `Bundler cannot safely replace gems in world-writeable directories due to
potential vulnerabilities.` issue. Cory thought this had helped in another case.

**Comment by jcoyne** [comment]
Yes, @corylown's fix works on regular type projects, but not those that use engine_cart. I was trying (unsuccessfully) to fix the same problem in Blacklight.  (see https://github.com/projectblacklight/blacklight/pull/3216)

**Comment by jcoyne** [comment]
I did notice the Ubuntu image version differed 20240708.1.0, vs 20240616.1.0 

As did the version of setup-ruby:
'ruby/setup-ruby@v1' (SHA:3783f195e29b74ae398d7caca108814bbafde90e) vs 'ruby/setup-ruby@v1' (SHA:161cd54b698f1fb3ea539faab2e036d409550e3c)

**Comment by jcoyne** [comment]
Potentially related to https://github.com/ruby/setup-ruby/issues/624

**Review by corylown — APPROVED** [review]

**Pull request merged**
