### PR TITLE
Update RIIIF to 2.0

### PR DESCRIPTION
**Pull request by jcoyne**

### CODE REVIEW

**Comment by mejackreed** [comment]
Does the riiif initializer need to change here at all? we have that deprecation warning that something will change in 2.0

**Comment by jcoyne** [comment]
Yes, that is unexpected given: https://github.com/projectblacklight/spotlight/blob/master/app/services/spotlight/carrierwave_file_resolver.rb#L4

**Comment by jcoyne** [comment]
Ah, there was a typo in that code. Should be fixed now.

**Comment by mejackreed** [comment]
Do you know if there are any breaking changes here we should worry about for our downstream consumers?

**Comment by jcoyne** [comment]
@mejackreed I don't know. I suspect that config change might be it.

**Comment by aeschylus** [comment]
```
Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (~> 5.1.6)
    blacklight-spotlight was resolved to 1.5.1, which depends on
      blacklight (~> 6.3) was resolved to 6.14.1, which depends on
        rails (< 6, >= 4.2)
    blacklight-spotlight was resolved to 1.5.1, which depends on
      rails (~> 5.1)
    engine_cart (~> 2.0) was resolved to 2.0.1, which depends on
      rails
Bundler could not find compatible versions for gem "riiif":
  In Gemfile:
    riiif (~> 1.0)
    blacklight-spotlight was resolved to 1.5.1, which depends on
      riiif (~> 2.0)
```

**Comment by aeschylus** [comment]
https://github.com/mbleigh/acts-as-taggable-on/pull/887

**Comment by no-reply** [comment]
Anyone know what's needed to complete this upgrade?

**Comment by dunn** [comment]
Can this be rebased?

**Comment by jcoyne** [comment]
@dunn it has been rebased.

**Comment by dunn** [comment]
Oop, right now the build is failing because of rubocop.

**Comment by jcoyne** [comment]
@dunn right, which is why I made https://github.com/projectblacklight/spotlight/pull/2135

**Comment by dunn** [comment]
The Rails 5.1/Ruby 2.4 build is consistently failing with:
```
     Selenium::WebDriver::Error::SessionNotCreatedError:
       session not created: This version of ChromeDriver only supports Chrome version 74
         (Driver info: chromedriver=74.0.3729.6 (255758eccf3d244491b8a1317aa76e1ce10d57e9-refs/branch-heads/3729@{#29}),platform=Linux 4.4.0-101-generic x86_64)
```
https://travis-ci.org/projectblacklight/spotlight/jobs/512607508#L3715

**Pull request merged**
