### PR TITLE
Allow paper_trail v12

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by thatbudakguy** [comment]
what's this for?

**Comment by cbeer** [comment]
We track model changes (e.g. https://github.com/projectblacklight/spotlight/blob/master/app/models/spotlight/page.rb#L38)  so we can revert stuff if needed. I don't think we've ever built out friendly tools, but being able to get previous revisions from the rails console is handy 🤷‍♂️

**Comment by thatbudakguy** [comment]
were we pinning it because of a different version constraint that's now resolved? just wondering why we now can use v12

**Comment by cbeer** [comment]
Ah. I think we were just pessimistically pinning the version in case there was a breaking change going from 11 -> 12, but there wasn't.

**Review by thatbudakguy — APPROVED** [review]

**Pull request merged**
