### PR TITLE
Subclass from ActionMailer::Base

### PR DESCRIPTION
**Pull request by mejackreed**
Resolves an issue we saw when deploying the latest v3.0.0.alpha.1

### CODE REVIEW

**Comment by cbeer** [comment]
Can you say more about the issue?

**Comment by mejackreed** [comment]
Sure.. (And maybe there is a better way to handle this). When deploying we are getting an error like:

```
01 # What actually happend?
01
01   We encountered a Ruby exception and were forced to cancel your request.
01
01 # Error details
01
01   NameError: uninitialized constant Spotlight::ApplicationMailer
01     ./shared/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/act…
01     ./shared/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/act…
01     ./shared/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/act…
01     ./shared/bundle/ruby/2.6.0/gems/bootsnap-1.4.5/lib/bootsnap/load_path_cache/core_ext/act…
01     ./shared/bundle/ruby/2.6.0/bundler/gems/spotlight-3c0f7ec8bb2d/app/mailers/spotlight/con…
01     ./shared/bundle/ruby/2.6.0/bundler/gems/spotlight-3c0f7ec8bb2d/app/mailers/spotlight/con…
```

**Comment by cbeer** [comment]
Can we just add `ApplicationMailer` to our app?  Rails should be generating it by default, I think.

**Comment by mejackreed** [comment]
That's right.. thanks for that.

**Pull request closed without merging**
