### PR TITLE
Add feature page Browse Group categories carousel

### PR DESCRIPTION
**Pull request by mejackreed**
Fixes https://github.com/sul-dlss/dlme/issues/1142

Kapture 2021-01-26 at 16 56 09
Kapture 2021-01-26 at 16 57 14

## On a feature page with no sidebar
Screen Shot 2021-01-26 at 5 01 44 PM

### CODE REVIEW

**Comment by mejackreed** [comment]
I've added an update based on feedback from @ggeisler to add support for 4 across when no sidebar is present

Kapture 2021-01-27 at 05 04 02

**Comment by mejackreed** [comment]
And some additional updates on vertical spacing:

## Before
Screen Shot 2021-01-27 at 5 28 00 AM

## After
Screen Shot 2021-01-27 at 5 27 44 AM

**Review by cbeer — APPROVED** [review]

**Review by ggeisler — COMMENTED** [review]
Nice. It's great to see the 4-up working for the no-sidebar scenario.

I'll note a few styling issues below, but can I also ask that you go back to the [ticket with design details](https://github.com/sul-dlss/dlme/issues/1142) and double-check that all of my specifications there are addressed (or note why they can't be done)? For instance, the previous/next buttons are too close together, and the design ticket specifies `1rem` between them (see section "C: Previous/Next buttons").

Some other things I see that might not have been specified but don't really match the mockups and ideally should:

- The group title, "View all" link, and the prev/next buttons should be bottom-aligned
- I could be wrong, but the spacing between the group title and the "View all" link doesn't appear to be the `~20px` suggested in section "A & B: Heading and associated link" of the design ticket
- On the mobile viewports where we should one tile at a time (which functionally looks great) ideally the tile should be centered in the viewport

If any of the items above or styling details in the design ticket are unclear or difficult to do, that's fine; I can take a pass at fine-tuning the styling after this PR is merged.

**Comment by mejackreed** [comment]
Thanks for the feedback @ggeisler . I've gone back through this and pushed up some changes to hopefully get closer here. Some added changes are:
 - Spacing in between next/previous
 - Larger icons on mobile for next/previous
 - Bottom aligned content
 - Spacing between heading and view all increased (note: using spacer class not pixel value)
 - Mobile centered tile and better padding
Screen Shot 2021-01-27 at 1 35 52 PM
Screen Shot 2021-01-27 at 1 37 18 PM

**Comment by ggeisler** [comment]
Excellent, thanks @mejackreed. If I see any other little styling things I'll just do a PR myself to adjust but this definitely looks like it takes care of the obvious things I was concerned about.

**Pull request merged**
