### PR TITLE
Merge spotlight_resources_iiif gem into this project

### PR DESCRIPTION
**Pull request by cbeer**

### CODE REVIEW

**Comment by jkeck** [comment]
Hmm, apparently it says that there is a conflict on rebase.  I kinda feel like we shouldn't squash this all into once commit.  What do you think @cbeer?

**Comment by cbeer** [comment]
Hm. I'll rebase and try again.

**Comment by cbeer** [comment]
Ugh -- git isn't tracking those early commits as against the subtree. I can try to redo the merge right, or we can just accept a squash merge. I'm slightly inclined to the latter, but doesn't really matter.

**Comment by jkeck** [comment]
I'm fine with that.  Probably more trouble that it is worth.

**Pull request merged**
