### PR TITLE
Turn off Naming/BlockForwarding Style/ArgumentsForwarding cops

### PR DESCRIPTION
**Pull request by corylown**
These got autocorrected with https://github.com/projectblacklight/spotlight/commit/ff59de9ac1246b0630bec371065608cfe3e1b835 but seems to break things.

### CODE REVIEW

**Comment by cbeer** [comment]
> seems to break things

What sort of things?

**Comment by corylown** [comment]
Closing for now. I think the error Niqui and I were seeing is related to something else.

**Comment by dnoneill** [comment]
I am pretty sure this breaks importing IIIF manifests

**Comment by dnoneill** [comment]
double checked on main. working. not sure what was happening yesterday

**Comment by dnoneill** [comment]
This is breaking again for me. I am not quite sure what is happening.

**Pull request closed without merging**
