### PR TITLE
This illustrates the fundamental problem with #205

### PR DESCRIPTION
**Pull request by jcoyne**
This behavior is triggered by `CatalogController#update` here:

https://github.com/projectblacklight/spotlight/blob/c0b782dda044faa6a724db18934f1063b3209cb7/app/controllers/spotlight/catalog_controller.rb#L78

### CODE REVIEW

**Comment by mjgiarlo** [comment]
@jcoyne I'm not sure I see the fundamental problem. This commit fixes the broken test:

https://github.com/projectblacklight/spotlight/pull/1509/commits/24be8c24e27d5da4a74d65079b8c677aab949d24

Is the fundamental problem the *names* of the hash keys? that's all I materiall changed in the spec.

**Comment by jcoyne** [comment]
@mjgiarlo no your fix is not valid.  It  should have a key like `spotlight_exhibit_slug_#{exhibit.slug}_bsi` and a key like `exhibit_#{exhibit.slug}_public_bsi`

**Comment by mjgiarlo** [comment]
@jcoyne OK, so the expectation should be that both the visibility fields and the filter fields *both* appear for each exhibit?

**Comment by jcoyne** [comment]
Yes. Both fields must be present.

**Comment by cbeer** [comment]
Yes - it's two different things:

- the filter field makes it available to the curator for the exhibit
- the visibility field makes it visible to the end users

**Comment by mjgiarlo** [comment]
OK, thanks, @jcoyne @cbeer. Closing this PR now.

**Pull request closed without merging**
