### PR TITLE
[WIP] put the spambot honeypot field name in the config to make usage clearer in the code

### PR DESCRIPTION
**Pull request by jmartin-sul**
as per @cbeer's suggestion.

if we want to go this route, i think i'd prefer to not merge this PR into that branch, but would rather just squash both commits into the the base exhibits-345 branch.  this is more of a convenient place to see the differences in the two approaches.

### CODE REVIEW

**Comment by jmartin-sul** [comment]
hmm, looks like the template part of this version needs some tweaking to keep from 500ing.  can't seem to read `Spotlight::Engine.config.spambot_honeypot_email_field`?

need to head out, will revisit tonight or tomorrow morning.

**Comment by jmartin-sul** [comment]
actually, this works, it turns out i just needed to restart my local instance for the config addition to get picked up.

**Comment by jmartin-sul** [comment]
here's what this branch looks like vs master (instead of vs its predecessor version like in this PR):
https://github.com/projectblacklight/spotlight/compare/exhibits-345-can-spam-feedback_config-field-name

opinion on this approach vs the one in PR #1654?  @cbeer, @jkeck?  i'm happy to go either way.

**Comment by cbeer** [comment]
Cool, thanks. I think this makes the intent clearer (even if it's because I wouldn't read the text around it.). Last question -- should those explanations be i18n strings?

**Pull request closed without merging**
