### PR TITLE
Make custom field facets limited by default.

### PR DESCRIPTION
**Pull request by tpendragon**

### CODE REVIEW

**Comment by tpendragon** [comment]
@cbeer Any idea what those failures are about?

**Comment by cbeer** [comment]
Bad/insufficient mocking in that helper. This is caused by https://github.com/projectblacklight/blacklight/commit/5bfe2ed42e89be3053b6c013901b107593865bb8 (backported into v6.8.).

**Comment by tpendragon** [comment]
@cbeer I added it to this PR. I can do another, if you really want.

**Comment by cbeer** [comment]
Thanks, this'll be fine.

**Pull request merged**
