### PR TITLE
Align and bold form col label ala BS3

### PR DESCRIPTION
**Pull request by mejackreed**
Fixes https://github.com/sul-dlss/exhibits/issues/1549

Screen Shot 2020-01-31 at 3 32 16 PM
Screen Shot 2020-01-31 at 3 31 57 PM

### CODE REVIEW

**Comment by cbeer** [comment]
I'm not thrilled with doing this in spotlight; it feels like bootstrap made a global choice that we don't agree with and we'd be better off providing our own theme locally to override it.

**Comment by mejackreed** [comment]
I'd be fine with that approach. :+1:

**Comment by mejackreed** [comment]
I'd be fine with that approach. :+1:

**Comment by mejackreed** [comment]
Going to go ahead and close this and look at doing this locally.

**Pull request closed without merging**
