### PR TITLE
Fix IndexingCompleteMailer#documents_indexed in Ruby 3

### PR DESCRIPTION
**Pull request by mcritchlow**
If a call is made to this method in Ruby 3, the following stacktrace and
error occurs. This happens when adding items to an exhibit by CSV.

```
spotlight-web-1         | I, [2023-03-27T14:33:44.654852 #7]  INFO -- : [ActiveJob] [Spotlight::AddUploadsFromCsv] [b191dbe9-d1a4-4d47-b108-4de9a197e709] Performing Spotlight::AddUploadsFromCsv (Job ID: b191dbe9-d1a4-4d47-b108-4de9a197e709) from Inline(default) enqueued at 2023-03-27T14:33:44Z with arguments: [{"identifier_tesim"=>"uarch112-g01579", "full_title_tesim"=>"Ednah A. Rich", "readonly_date-statement_tesim"=>"May 1916", "type_tesim"=>"Photograph", "readonly_holding-institution_tesim"=>"University Archives Photographs Collection, University Archives, Special Research Collections, UCSB Library", "readonly_collection_tesim"=>"The Anna S. C. Blake Manual Training School: The Remarkable Antecedent of UC Santa Barbara", "file"=>"cusb-uarch112-g01579-1-m.tif"}, {"identifier_tesim"=>"uarch112-g01582", "full_title_tesim"=>"Group photograph in front of Anna S. C. Blake Manual Training School", "readonly_date-statement_tesim"=>"early 20th century", "type_tesim"=>"Photograph", "readonly_holding-institution_tesim"=>"University Archives Photographs Collection, University Archives, Special Research Collections, UCSB Library", "readonly_collection_tesim"=>"The Anna S. C. Blake Manual Training School: The Remarkable Antecedent of UC Santa Barbara", "file"=>"cusb-uarch112-g01582-1-m.tif"}, {"identifier_tesim"=>"uarch112-g01650", "full_title_tesim"=>"Miss Anna S.C. Blake", "readonly_date-statement_tesim"=>"late 19th century", "type_tesim"=>"Photograph", "readonly_holding-institution_tesim"=>"University Archives Photographs Collection, University Archives, Special Research Collections, UCSB Library", "readonly_collection_tesim"=>"The Anna S. C. Blake Manual Training School: The Remarkable Antecedent of UC Santa Barbara", "file"=>"cusb-uarch112-g01650-1-m.tif"}, {"identifier_tesim"=>"uarch112-g01668", "full_title_tesim"=>"Anna S. C. Blake Manual Training School", "readonly_date-statement_tesim"=>"early 20th century", "type_tesim"=>"Photograph", "readonly_holding-institution_tesim"=>"University Archives Photographs Collection, University Archives, Special Research Collections, UCSB Library", "readonly_collection_tesim"=>"The Anna S. C. Blake Manual Training School: The Remarkable Antecedent of UC Santa Barbara", "file"=>"cusb-uarch112-g01668-1-m.tif"}, {"identifier_tesim"=>"uarch112-g01698", "full_title_tesim"=>"Students with completed projects at the Blake Manual Training School", "readonly_date-statement_tesim"=>"early 20th century", "type_tesim"=>"Photograph", "readonly_holding-institution_tesim"=>"University Archives Photographs Collection, University Archives, Special Research Collections, UCSB Library", "readonly_collection_tesim"=>"The Anna S. C. Blake Manual Training School: The Remarkable Antecedent of UC Santa Barbara", "file"=>"cusb-uarch112-g01698-1-m.tif"}, {"identifier_tesim"=>"uarch112-g01705", "full_title_tesim"=>"Young students at desks, Blake Manual Training School", "readonly_date-statement_tesim"=>"early 20th century", "type_tesim"=>"Photograph", "readonly_holding-institution_tesim"=>"University Archives Photographs Collection, University Archives, Special Research Collections, UCSB Library", "readonly_collection_tesim"=>"The Anna S. C. Blake Manual Training School: The Remarkable Antecedent of UC Santa Barbara", "file"=>"cusb-uarch112-g01705-1-m.tif"}, {"identifier_tesim"=>"uarch112-g01722", "full_title_tesim"=>"Two woman working on looms, Blake Manual Training School", "readonly_date-statement_tesim"=>"early 20th century", "type_tesim"=>"Photograph", "readonly_holding-institution_tesim"=>"University Archives Photographs Collection, University Archives, Special Research Collections, UCSB Library", "readonly_collection_tesim"=>"The Anna S. C. Blake Manual Training School: The Remarkable Antecedent of UC Santa Barbara", "file"=>"cusb-uarch112-g01722-1-m.tif"}, {"identifier_tesim"=>"uarch112-g01725", "full_title_tesim"=>"Cooking class, Blake Manual Training School", "readonly_date-statement_tesim"=>"early 20th century", "type_tesim"=>"Photograph", "readonly_holding-institution_tesim"=>"University Archives Photographs Collection, University Archives, Special Research Collections, UCSB Library", "readonly_collection_tesim"=>"The Anna S. C. Blake Manual Training School: The Remarkable Antecedent of UC Santa Barbara", "file"=>"cusb-uarch112-g01725-1-m.tif"}, {"identifier_tesim"=>"uarch112-g01726", "full_title_tesim"=>"Sewing class, Blake Manual Training School", "readonly_date-statement_tesim"=>"early 20th century", "type_tesim"=>"Photograph", "readonly_holding-institution_tesim"=>"University Archives Photographs Collection, University Archives, Special Research Collections, UCSB Library", "readonly_collection_tesim"=>"The Anna S. C. Blake Manual Training School: The Remarkable Antecedent of UC Santa Barbara", "file"=>"cusb-uarch112-g01726-1-m.tif"}, {"identifier_tesim"=>"uarch112-g01728", "full_title_tesim"=>"Art room, Blake Manual Training School", "readonly_date-statement_tesim"=>"early 20th century", "type_tesim"=>"Photograph", "readonly_holding-institution_tesim"=>"University Archives Photographs Collection, University Archives, Special Research Collections, UCSB Library", "readonly_collection_tesim"=>"The Anna S. C. Blake Manual Training School: The Remarkable Antecedent of UC Santa Barbara", "file"=>"cusb-uarch112-g01728-1-m.tif"}], #<GlobalID:0x00007fed12301180 @uri=#<URI::GID gid://app/Spotlight::Exhibit/1>>, #<GlobalID:0x00007fed123003c0 @uri=#<URI::GID gid://app/User/1>>
spotlight-web-1         | D, [2023-03-27T14:33:44.655741 #7] DEBUG -- : [ActiveJob] [Spotlight::AddUploadsFromCsv] [b191dbe9-d1a4-4d47-b108-4de9a197e709]   Spotlight::JobTracker Load (0.2ms)  SELECT "spotlight_job_trackers".* FROM "spotlight_job_trackers" WHERE "spotlight_job_trackers"."job_id" = $1 LIMIT $2  [["job_id", "b191dbe9-d1a4-4d47-b108-4de9a197e709"], ["LIMIT", 1]]
spotlight-web-1         | D, [2023-03-27T14:33:44.669127 #7] DEBUG -- : [ActiveJob] [Spotlight::AddUploadsFromCsv] [b191dbe9-d1a4-4d47-b108-4de9a197e709]   TRANSACTION (0.2ms)  BEGIN
spotlight-web-1         | D, [2023-03-27T14:33:44.671634 #7] DEBUG -- : [ActiveJob] [Spotlight::AddUploadsFromCsv] [b191dbe9-d1a4-4d47-b108-4de9a197e709]   Spotlight::JobTracker Create (0.5ms)  INSERT INTO "spotlight_job_trackers" ("on_type", "on_id", "resource_type", "resource_id", "job_id", "job_class", "status", "data", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING "id"  [["on_type", "Spotlight::Exhibit"], ["on_id", 1], ["resource_type", "Spotlight::Exhibit"], ["resource_id", 1], ["job_id", "b191dbe9-d1a4-4d47-b108-4de9a197e709"], ["job_class", "Spotlight::AddUploadsFromCsv"], ["status", "in_progress"], ["data", "--- {}\n"], ["created_at", "2023-03-27 14:33:44.668592"], ["updated_at", "2023-03-27 14:33:44.668592"]]
spotlight-web-1         | D, [2023-03-27T14:33:44.677285 #7] DEBUG -- : [ActiveJob] [Spotlight::AddUploadsFromCsv] [b191dbe9-d1a4-4d47-b108-4de9a197e709]   TRANSACTION (1.2ms)  COMMIT
spotlight-web-1         | D, [2023-03-27T14:33:44.685450 #7] DEBUG -- : [ActiveJob] [Spotlight::AddUploadsFromCsv] [b191dbe9-d1a4-4d47-b108-4de9a197e709] Spotlight::IndexingCompleteMailer#documents_indexed: processed outbound mail in 4.3ms
spotlight-web-1         | D, [2023-03-27T14:33:44.686790 #7] DEBUG -- : [ActiveJob] [Spotlight::AddUploadsFromCsv] [b191dbe9-d1a4-4d47-b108-4de9a197e709]   TRANSACTION (0.2ms)  BEGIN
spotlight-web-1         | D, [2023-03-27T14:33:44.689203 #7] DEBUG -- : [ActiveJob] [Spotlight::AddUploadsFromCsv] [b191dbe9-d1a4-4d47-b108-4de9a197e709]   Spotlight::JobTracker Update (0.3ms)  UPDATE "spotlight_job_trackers" SET "status" = $1, "data" = $2, "updated_at" = $3 WHERE "spotlight_job_trackers"."id" = $4  [["status", "completed"], ["data", "---\n:progress: 0\n:total: 100\n"], ["updated_at", "2023-03-27 14:33:44.685856"], ["id", 1]]
spotlight-web-1         | D, [2023-03-27T14:33:44.694336 #7] DEBUG -- : [ActiveJob] [Spotlight::AddUploadsFromCsv] [b191dbe9-d1a4-4d47-b108-4de9a197e709]   TRANSACTION (1.6ms)  COMMIT
spotlight-web-1         | E, [2023-03-27T14:33:44.700169 #7] ERROR -- : [ActiveJob] [Spotlight::AddUploadsFromCsv] [b191dbe9-d1a4-4d47-b108-4de9a197e709] Error performing Spotlight::AddUploadsFromCsv (Job ID: b191dbe9-d1a4-4d47-b108-4de9a197e709) from Inline(default) in 45.07ms: ArgumentError (wrong number of arguments (given 4, expected 3)):
spotlight-web-1         | /spotlight/engine/app/mailers/spotlight/indexing_complete_mailer.rb:8:in `documents_indexed'
spotlight-web-1         | /usr/local/bundle/gems/actionpack-6.1.7.3/lib/abstract_controller/base.rb:228:in `process_action'
spotlight-web-1         | /usr/local/bundle/gems/actionpack-6.1.7.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
spotlight-web-1         | /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
spotlight-web-1         | /usr/local/bundle/gems/actiontext-6.1.7.3/lib/action_text/rendering.rb:20:in `with_renderer'
spotlight-web-1         | /usr/local/bundle/gems/actiontext-6.1.7.3/lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
spotlight-web-1         | /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `instance_exec'
spotlight-web-1         | /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
spotlight-web-1         | /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/callbacks.rb:137:in `run_callbacks'
spotlight-web-1         | /usr/local/bundle/gems/actionpack-6.1.7.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
spotlight-web-1         | /usr/local/bundle/gems/actionpack-6.1.7.3/lib/abstract_controller/base.rb:165:in `process'
spotlight-web-1         | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/rescuable.rb:25:in `block in process'
spotlight-web-1         | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
spotlight-web-1         | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/rescuable.rb:24:in `process'
spotlight-web-1         | /usr/local/bundle/gems/actionview-6.1.7.3/lib/action_view/rendering.rb:39:in `process'
spotlight-web-1         | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/base.rb:615:in `block in process'
spotlight-web-1         | /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `block in instrument'
spotlight-web-1         | /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
spotlight-web-1         | /usr/local/bundle/gems/activesupport-6.1.7.3/lib/active_support/notifications.rb:203:in `instrument'
spotlight-web-1         | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/base.rb:614:in `process'
spotlight-web-1         | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/message_delivery.rb:128:in `block in processed_mailer'
spotlight-web-1         | <internal:kernel>:90:in `tap'
spotlight-web-1         | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/message_delivery.rb:127:in `processed_mailer'
spotlight-web-1         | /usr/local/bundle/gems/actionmailer-6.1.7.3/lib/action_mailer/message_delivery.rb:118:in `deliver_now'
spotlight-web-1         | /spotlight/engine/app/jobs/spotlight/add_uploads_from_csv.rb:20:in `block in <class:AddUploadsFromCsv>'
```

Request params:

```ruby
{"authenticity_token"=>"[FILTERED]",
 "resources_csv_upload"=>
  {"url"=>
    #<ActionDispatch::Http::UploadedFile:0x00007fed18fe6688
     @content_type="text/csv",
     @headers="Content-Disposition: form-data; name=\"resources_csv_upload[url]\"; filename=\"blake_template.csv\"\r\n" + "Content-Type: text/csv\r\n",
     @original_filename="blake_template.csv",
     @tempfile=#<File:/tmp/RackMultipart20230327-7-nw9f9b.csv (closed)>>},
 "commit"=>"Add item",
 "exhibit_id"=>"my-exhibit"}
```

### CODE REVIEW

**Comment by jcoyne** [comment]
@mcritchlow we've been using this code on ruby 3 with no problem. Can you explain how you are triggering it? Is it possible that you have messages in the queue that were produced on an old version of the code that were left in the queue and are processable with the new code?

**Comment by mcritchlow** [comment]
@jcoyne - I encountered this initially in a MR to our spotlight application upgrading the version of Ruby to 3.2.1 (from 2.7.7).

We have a system test that does a CSV upload and triggers this error consistently https://gitlab.com/surfliner/surfliner/-/merge_requests/3021 (job error: https://gitlab.com/surfliner/surfliner/-/jobs/3998118251#L1779)

I spun up a clean (docker-compose) spotlight test app, created an exhibit, and then uploaded a csv and can also trigger this error consistently.

I am admittedly baffled by the error honestly. I'm aware of the ruby 3 kwargs changes, but those didn't _seem_ relevant here. I tried a few variations of the method definition (such as making all the arguments keyword arguments) to no avail.

I was hoping to create a system/integration test demonstrating this, but the docker-compose environment seems to be missing some configuration/gems needed to run rspec locally.

**Comment by jcoyne** [comment]
It kind of looks like this bug in rails that they aren't going to fix (because it's in 6.1).  One of the core maintainers said that Rails 6.1 does not work with Ruby 3.2: https://github.com/rails/rails/issues/46883#issuecomment-1371325906

**Comment by mcritchlow** [comment]
> It kind of looks like this bug in rails that they aren't going to fix (because it's in 6.1): [rails/rails#46883](https://github.com/rails/rails/issues/46883). One of the core maintainers said that Rails 6.1 does not work with Ruby 3.2: [rails/rails#46883 (comment)](https://github.com/rails/rails/issues/46883#issuecomment-1371325906)

oh wild.. i should have considered Rails could be implicated in this, but hadn't. That definitely looks similar. Thank you.

**Pull request closed without merging**
